FROM python:3.6.12-alpine3.12
WORKDIR /app

COPY update_db/. ./
RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install -r requirements.txt

#RUN Startup.sh

RUN crontab crontab

EXPOSE 50000


CMD ["crond", "-f"]