services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: react-flask-app-backend
    container_name: backend
    environment:
      APP_PORT: 5000
      DB_PORT_8086_TCP_ADDR: 'influxdb'
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    depends_on:
      - influxdb

  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: react-flask-app-client
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - frontend


  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2 
      - influxdb_config:/etc/influxdb2 
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - INFLUXDB_DB=mydb
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword1      
      - INFLUXD_INIT_PORT=8086
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    container_name: influxdb
    networks:
      - backend


  update:
    build:
      context: .
      dockerfile: Dockerfile.update
    image: react-flask-app-backend-update
    container_name: db_update
    ports:
      - "50000:50000"
    networks:
      - backend
    volumes:
      - load_db_app:/app
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  influxdb_config:
  load_db_app:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
