FROM python:3.9
WORKDIR /app

COPY backend/requirements.txt backend/.flaskenv backend/config.py backend/password_file.py backend/wsgi.py ./
COPY  backend/flaskr  flaskr


RUN pip install -r ./requirements.txt
RUN pip install gunicorn
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "wsgi:app"]