services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: react-flask-app-backend
    container_name: backend
    environment:
      - DB_HOST_NAME=container_postgres
      - DATABASE_PORT=5432
      - DB_PASSWORD=teD#5ck2TJHW
      - DB_NAME=postgres
      - DB_USER=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    depends_on:
      - postgres
    volumes:
      - ./backend/tests:/app/tests
      - ./backend:/app  

  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: react-flask-app-client
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - frontend



  postgres:
    container_name: container_postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=teD#5ck2TJHW
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
     - postgres-db:/var/lib/postgresql/data
    networks:
      - backend

  update:
    build:
      context: .
      dockerfile: Dockerfile.update
    image: react-flask-app-backend-update
    container_name: db_update
    environment:
      - DB_HOST_NAME=postgres
      - DATABASE_PORT=5432
      - DB_PASSWORD=teD#5ck2TJHW
      - DB_NAME=US_tresaury_visualizer
      - DB_USER=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "50000:50000"
    networks:
      - backend
    depends_on:
      - postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - backend

volumes:
 postgres-db:
  


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
